version: '3'

services: # We have 3 containers
  html_webserver:
    image: httpd:latest # First container runs the html login form
    ports:
      - "8080:80" 
    volumes:
      - ./apache/html:/usr/local/apache2/htdocs  # Accesses the files in the /apache/html directory 
  
  detection_algorithm: 
    build:
      context: ./Detection
    image: detection 
    container_name: detection_Container
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock

  cpp_webserver: # The webserver that validate.cpp runs on when the html form gets submitted
    build: # Form is submitted to this page http://localhost:8081/cgi-bin/validate, which is run on this webserver
      context: ./apache2
    ports:
      - "8081:80" 
    volumes:
      - ./shared:/usr/lib/cgi-bin
    depends_on:
      - application

  application:
    build:
      context: ./application
    volumes:
      - ./shared:/usr/src/ # shared volume that the compiled version of validate.cpp is stored in
